db.exercicios.insertMany([
    {Codigo_Exercicio: 1.0, Repeticoes: 12, Nome_Exercicio: 'Voador', Grupo_Muscular: 'A'},
    {Codigo_Exercicio: 2.0, Repeticoes: 12, Nome_Exercicio: 'Supino inclinado com barra', Grupo_Muscular: 'A'},
    {Codigo_Exercicio: 3.0, Repeticoes: 12, Nome_Exercicio: 'Crucifixo reto', Grupo_Muscular: 'A'},
    {Codigo_Exercicio: 4.0, Repeticoes: 11, Nome_Exercicio: 'Supino reto com barra', Grupo_Muscular: 'A'},
    {Codigo_Exercicio: 5.0, Repeticoes: 10, Nome_Exercicio: 'Tr?ceps Voador', Grupo_Muscular: 'A'},
    {Codigo_Exercicio: 6.0, Repeticoes: 10, Nome_Exercicio: 'Tr?ceps Corda Cross', Grupo_Muscular: 'A'},
    {Codigo_Exercicio: 7.0, Repeticoes: 12, Nome_Exercicio: 'Polichinelo', Grupo_Muscular: 'A'},
    {Codigo_Exercicio: 8.0, Repeticoes: 10, Nome_Exercicio: 'Flex?o', Grupo_Muscular: 'A'},
    {Codigo_Exercicio: 9.0, Repeticoes: 11, Nome_Exercicio: 'Tr?ceps Barra Cross', Grupo_Muscular: 'A'},
    {Codigo_Exercicio: 10.0, Repeticoes: 12, Nome_Exercicio: 'Tr?ceps Testa', Grupo_Muscular: 'A'},
    {Codigo_Exercicio: 11.0, Repeticoes: 11, Nome_Exercicio: 'Levantamento terra', Grupo_Muscular: 'B'},
    {Codigo_Exercicio: 12.0, Repeticoes: 12, Nome_Exercicio: 'Pulley Frontal', Grupo_Muscular: 'B'},
    {Codigo_Exercicio: 13.0, Repeticoes: 11, Nome_Exercicio: 'Pulley Atr?s', Grupo_Muscular: 'B'},
    {Codigo_Exercicio: 14.0, Repeticoes: 11, Nome_Exercicio: 'Remada Baixa', Grupo_Muscular: 'B'},
    {Codigo_Exercicio: 15.0, Repeticoes: 12, Nome_Exercicio: 'Serrote', Grupo_Muscular: 'B'},
    {Codigo_Exercicio: 16.0, Repeticoes: 10, Nome_Exercicio: 'Rosca Alternada com Banco inclinado', Grupo_Muscular: 'B'},
    {Codigo_Exercicio: 17.0, Repeticoes: 11, Nome_Exercicio: 'Rosca Scott barra W', Grupo_Muscular: 'B'},
    {Codigo_Exercicio: 18.0, Repeticoes: 10, Nome_Exercicio: 'Rosca direita barra Reta', Grupo_Muscular: 'B'},
    {Codigo_Exercicio: 19.0, Repeticoes: 12, Nome_Exercicio: 'Martelo em p?', Grupo_Muscular: 'B'},
    {Codigo_Exercicio: 20.0, Repeticoes: 11, Nome_Exercicio: 'Rosca Punho', Grupo_Muscular: 'B'},
    {Codigo_Exercicio: 21.0, Repeticoes: 11, Nome_Exercicio: 'Leg press 45?', Grupo_Muscular: 'C'},
    {Codigo_Exercicio: 22.0, Repeticoes: 12, Nome_Exercicio: 'Extensor de pernas', Grupo_Muscular: 'C'},
    {Codigo_Exercicio: 23.0, Repeticoes: 10, Nome_Exercicio: 'Flexora Sentada', Grupo_Muscular: 'C'},
    {Codigo_Exercicio: 24.0, Repeticoes: 12, Nome_Exercicio: 'Adutora', Grupo_Muscular: 'C'},
    {Codigo_Exercicio: 25.0, Repeticoes: 12, Nome_Exercicio: 'Abdutora', Grupo_Muscular: 'C'},
    {Codigo_Exercicio: 26.0, Repeticoes: 12, Nome_Exercicio: 'Stiff', Grupo_Muscular: 'C'},
    {Codigo_Exercicio: 27.0, Repeticoes: 11, Nome_Exercicio: 'Desenvolvimento nuca com Barra', Grupo_Muscular: 'C'},
    {Codigo_Exercicio: 28.0, Repeticoes: 12, Nome_Exercicio: 'Desenvolvimento Maquina', Grupo_Muscular: 'C'},
    {Codigo_Exercicio: 29.0, Repeticoes: 11, Nome_Exercicio: 'Eleva??o frontal com halteres em p?', Grupo_Muscular: 'C'},
    {Codigo_Exercicio: 30.0, Repeticoes: 11, Nome_Exercicio: 'Eleva??o lateral com halteres sentado', Grupo_Muscular: 'C'}
    ])
    